/* Establecer una relacion que despliegue las capitales de las provinvias */

predicates
	provincia(symbol, string)
clauses
	provincia(panama, "Panama").
	provincia(chiriqui, "David").
	provincia(santos, "Las Tablas").
	provincia(bocasdeltoro, "Bocas del Toro").
	provincia(cocle, "Penonome").
	provincia(colon, "Colon").
	provincia(panamaoeste, "La Chorrera").
	provincia(herrera, "Chitre").
	provincia(veraguas, "Santiago").
	provincia(darien, "La Palma").